### ISSUE TITLE
Prevent losing focus after completion

### ISSUE THREAD

**Issue by kendallroth** [viclafouch/mui-otp-input#1]
Currently when the last character is entered, the focus is shifted somewhere unknown. Instead, the focus should either remain in the last input _or_ have a configuration option to do so. This can be a bit confusing as users can lose their focus when navigating around a form with an OTP component included (ie. if used as a PIN in a lengthier form).

**Comment by viclafouch** [comment]
Hey @kendallroth !

Thanks ! FIxed in https://github.com/viclafouch/mui-otp-input/releases/tag/v1.0.4
