### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Demetri0** [viclafouch/mui-otp-input#11]
Delete button doesn't delete right part of code

Example:
`[1] [2] [3|] [4] [5] [6]`

`|` - is cursor, pressing `Delete` does nothing. Expected behavior: It should cycle delete chars from the right part

---

Paste value from clipboard doesn't work correct way when not the first field(_fields from 2–6_) in the focus (in case Boxes to left is empty). It cuts value depending on which field we are focused.

p/s: Probably prepend with spaces? not sure...

---

Focus lost after fill the last Box - so I cannot erase value anymore, without manually returning focus using mouse, shift+tab also sets the focus to previous Box (length - 1)

---

onBlur triggers for each Box, that triggers full field validation and in a couple with for example Yup + react-hook-form, if we have validation rule that length of this field should be exactly 6 chars - error appears right after we enter first char into first Box.

Expected behavior: onBlur should not be triggered if any of Boxes has a focus

---

`Home` and `End` keys don't move cursor to first/last Box, it only move cursor within currently focused Box

---

`Tab` key moves cursor between Boxes

Expected behavior: Tab key should move focus to fields/buttons before/after `<MuiOtpInput />`, it should behave the same way like group of radio inputs with the same name, because semantically it is one field, but not 6 different fields.

**Comment by viclafouch** [comment]
Hey @Demetri0 

Thanks a lot for the catches ! 

Is it possible to create multiple issues in order for me to track correctly every problems plz ;)

**Comment by Demetri0** [comment]
Sure. Splitted.
