### ISSUE TITLE
Delete button doesn't delete right part of code

### ISSUE THREAD

**Issue by Demetri0** [viclafouch/mui-otp-input#13]
Delete button doesn't delete right part of code

Example:
`[1] [2] [3|] [4] [5] [6]`

`|` - is cursor, pressing `Delete` does nothing. Expected behavior: It should cycle delete chars from the right part

**Comment by viclafouch** [comment]
So to be sure, what would be the result ?

```
[1] [2] [3] [4] [5] []
```

And 5 is selected ?

**Comment by Demetri0** [comment]
Not sure should we actually move focus to the end or keep current (`[3]`) field.
But since we are currently at `[3]` field, i think `Delete` should remove the next value to cursor, so the state after pressing `Delete` button should be:

`[1] [2] [3|] [5] [6] [ ]`

**Comment by viclafouch** [comment]
`[1] [2] [3|] [ ] [ ] [ ]`

why the 3 is not deleted ?

**Comment by viclafouch** [comment]
that seems very confusing how you manage it

**Comment by Demetri0** [comment]
I've described there: https://github.com/viclafouch/mui-otp-input/issues/20#issuecomment-1598664273

**Comment by viclafouch** [comment]
Duplicated with #20
