### ISSUE TITLE
Paste value from clipboard doesn't work correct way when not the first field in focus

### ISSUE THREAD

**Issue by Demetri0** [viclafouch/mui-otp-input#14]
Paste value from clipboard doesn't work correct way when not the first field(_fields from 2–6_) in the focus, and Boxes to left is empty. 
It cuts value depending on which field we are focused.

Example:
Initial state:
`[ ] [ ] [ ] [| ] [ ] [ ]` - `|` cursor there, user press `Ctrl`+`v` with `123456` in the clipboard.

Then the next state appears (tested on [home page](https://viclafouch.github.io/mui-otp-input/)):
`[1] [2] [3] [ ] [ ] [ ]`

It is correct that we are trying to append value starts from corresponding field, but the problem here is that first 3 Boxes are empty, probably need to prepend with spaces in this case? I don't know the correct way to solve it, maybe you have some idea? or maybe it should be solved by the client code somehow?

**Comment by viclafouch** [comment]
Hey ! 

Ty ! 

What would be the correct result ?

**Comment by Demetri0** [comment]
The behavior that I expect is:

Before:
`[ ] [ ] [ ] [| ] [ ] [ ]`

Ctrl+v (`123456` in the clipboard):
[ ] [ ] [ ] [1] [2] [3]

**Comment by viclafouch** [comment]
This is not possible as the value is a `string`.

Like what should be the return value ?  `123` ? That's not correct
