### ISSUE TITLE
onBlur should not be triggered for each Box, but only once, when no Boxes focused

### ISSUE THREAD

**Issue by Demetri0** [viclafouch/mui-otp-input#16]
onBlur triggers for each Box, that triggers full field validation and in a couple with for example Yup + react-hook-form, if we have validation rule that length of this field should be exactly 6 chars - error appears right after we enter first char into first Box.

Expected behavior: onBlur should not be triggered if any of Boxes has a focus

**Comment by Demetri0** [comment]
At the moment of any of our fields lost focus, but we need some check that next focused element not one of our fields.

**Comment by viclafouch** [comment]
Fixed in https://github.com/viclafouch/mui-otp-input/releases/tag/v1.2.5 ! 

Thanks !
