### ISSUE TITLE
`Tab` key should not move cursor between Boxes, but should move to previous/next field that placed before/after OTPInput

### ISSUE THREAD

**Issue by Demetri0** [viclafouch/mui-otp-input#18]
`Tab` key moves cursor between Boxes

Expected behavior: Tab key should move focus to fields/buttons before/after `<MuiOtpInput />`, it should behave the same way like group of radio inputs with the same name, because semantically it is one field, but not 6 different fields.

I don't know any UX researches, it is just my opinion, so this issue only for up discussion.

**Comment by viclafouch** [comment]
I'm not sure about accessibility for this one..
