### ISSUE TITLE
validateChar function on paste

### ISSUE THREAD

**Issue by Melancholism** [viclafouch/mui-otp-input#22]
Hi,
`validateChar` function does not trigger on **paste** event.

This is my function:
```js
function matchIsNumeric(text) {
	console.log({ text });
	return !isNaN(Number(text));
}
const validateChar = (value, index) => matchIsNumeric(value);
```
And then I use this function on the `MuiOtpInput` component like below:

```js
<MuiOtpInput
validateChar={validateChar}
length={4}
/>
``` 
But when I copy a sample text like `abcd` and paste it in the input, the validation does not work and the value gets changed to `abcd`.

Am I doing anything wrong or is it an issues?

**Comment by viclafouch** [comment]
Hello @Melancholism  ! 

Nice catch ! Let me fix that !

**Comment by Melancholism** [comment]
@viclafouch Sorry to bother you again. when can we expect this issue to be solved? I'm really looking forward to this. Thanks.

**Comment by Melancholism** [comment]
@viclafouch  Thanks a lot for your attention and fast reply.
