### ISSUE TITLE
Issue with Jest testing

### ISSUE THREAD

**Issue by samatt1234** [viclafouch/mui-otp-input#25]
Hi Victor,

Thank you for building this library. 
Just an issue whilst testing on Jest. I am getting the following when testing my component using MUIOtpInput

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `ForwardRef`.
```

For now, I mocked your library to make my tests pass:  `jest.mock('mui-one-time-password-input')` but I am wondering whether you have a fix for this? 

I saw you were using ForwardRef a lot in your code, but you probably know it better than I do. Thanks

**Comment by viclafouch** [comment]
Hey ! I don't know why you have this error, I don't see any problem with the render as the code is working in dev mode.. So I'm very confused here

**Comment by lsafer-meemer** [comment]
This error happens when using react manually.

I encountered this issue while trying to use it with `kotlin/js`

**Comment by viclafouch** [comment]
Hello ! Could you try with the last version plz ?

**Comment by lsafer-meemer** [comment]
Thank you very much. Problem fixed now!

Interesting that just dropping `umd` support fixes the issue for me. If you got time would you please explain why for me? 😅

**Comment by lsafer-meemer** [comment]
I tried previously to inspect the object returned from the library it is the same object returned when I tried the library with `next.js`
yet `react` does not accept it in `kotlin/js`

I thought it got something to do with react version. I thought there is two instances of the react library and the `forwardRef` symbol is different between these instances. I was lazy to match react versions. But, just dropping `umd` support without even changing any library version fixed the issue.

**Comment by viclafouch** [comment]
There is some weird bugs with UMD and Material UI, that's why... 

So I just dropped it

**Comment by samatt1234** [comment]
Hi Victor,

After upgrading to the latest version, I am getting this error whilst using Playwright:

```
SyntaxError: Named export 'MuiOtpInput' not found. The requested module 'mui-one-time-password-input' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mui-one-time-password-input';
const { MuiOtpInput } = pkg;
```

I tried importing your component the way mentioned above but it doesn't work neither. Any ideas?

**Comment by samatt1234** [comment]
Adding to new issue since this one is closed

**Comment by samatt1234** [comment]
Also, I did not get the chance to test the update on Jest, since moving to Vitest instantaneously solved it
