### ISSUE TITLE
How to open the number pad when inputting in mobile devices?

### ISSUE THREAD

**Issue by jaffymaglinte** [viclafouch/mui-otp-input#26]
I want the use when they click the otp number key board should be open instead of the whole alphabet. I guess there was no option in the documentation. Do have any suggestion how can I achieve this?

**Comment by viclafouch** [comment]
Hello ! 

It's just html : 

```tsx
<MuiOtpInput value={otp} onChange={handleChange} TextFieldsProps={{   inputMode: 'numeric' }} />
```
