### ISSUE TITLE
Playwright issue

### ISSUE THREAD

**Issue by samatt1234** [viclafouch/mui-otp-input#28]
Hi Victor,

After upgrading to the latest version, I am getting this error whilst using Playwright:

SyntaxError: Named export 'MuiOtpInput' not found. The requested module 'mui-one-time-password-input' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

```
SyntaxError: Named export 'MuiOtpInput' not found. The requested module 'mui-one-time-password-input' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mui-one-time-password-input';
const { MuiOtpInput } = pkg;
```

I tried importing your component the way mentioned above but it doesn't work neither: 

```
import { jsx as E } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Any ideas?

Side note: My package.json does include type="module"

**Comment by brandaspt** [comment]
I'm having the same issue

**Comment by virendra-koloapp** [comment]
facing the same issues
![image](https://github.com/viclafouch/mui-otp-input/assets/119936949/6fa771f7-c961-49dc-b354-51cfc352fabf)

**Comment by viclafouch** [comment]
Hello ! Do you have a codesandbox for reproduction plz ?

**Comment by furrinub** [comment]
I am facing the same problem. mui-one-time-password-input.es.js in ./dist folder contains `import` statements which require us to put "type": "module" in our `package.json`. However, most of the other npm libraries use `require` statements which cannot exist in ES module (it is possible if I rename the file extension to .cjs but it means I need to change many files in my mode_modules).

Can you export your library to use `require` statements instead?

**Comment by b1997oct** [comment]
> Hello ! Do you have a codesandbox for reproduction plz ?

using in next js that error coming

**Comment by saikrishnabanda5** [comment]
Please resolve this issue

**Comment by viclafouch** [comment]
> > Hello ! Do you have a codesandbox for reproduction plz ?
> 
> using in next js that error coming

Please see https://github.com/viclafouch/mui-otp-input/issues/31

But no more CJS export (with `require`), it's an ESM package first..
