### ISSUE TITLE
How to overwrite input border style on focused?

### ISSUE THREAD

**Issue by jaffyyyy** [viclafouch/mui-otp-input#29]
I use to modify it like this but the border wont change when input is focused it only sticks to border: 1px solid #000;
So I was wondering how to override this.
```

export const OtpInputWrapper = styled(MuiOtpInput)`
  &&& {
    justify-content: center;
    gap: 7px; 

    .MuiOutlinedInput-notchedOutline {
      border: 1px solid #000;

      &:focus { // this part isn't working
        border: 2px solid #000 !important;
      }
    }

    .MuiOutlinedInput-input {
      font-size: 28px;
      height: 56px;
      width: 41px;
      padding: 0;
      font-weight: 600;
    }
  }
`;
```

**Comment by kameshdhana** [comment]
> Fixed it! thanks
> 
> ```
>     .MuiOutlinedInput-notchedOutline {
>       border: 1px solid #000;
>     }
> 
>     .Mui-focused {
>       border: 1.5px solid #000 !important;
>     }
> ```

If I use this autofocus is not working
