### ISSUE TITLE
I cannot set inputProps as numeric type for MuiOtpInput

### ISSUE THREAD

**Issue by SFaraji** [viclafouch/mui-otp-input#32]
I am attempting to use the `inputProps` prop with the `MuiOtpInput` component from `mui-one-time-password-input`. I have set the `inputMode` attribute to `"numeric"` for each input field, aiming to display the numeric keyboard on mobile devices.

Here's the code snippet I'm using:

```
<MuiOtpInput 
  value={otp} 
  onChange={handleChange}         
  inputProps={[    { inputMode: 'numeric' },    { inputMode: 'numeric' },    { inputMode: 'numeric' },    { inputMode: 'numeric' },  ]}
/>

```

Here also my `handleChange` function:

      const handleChange = async (newValue) => {
        setOTP(newValue);
        console.log(newValue);
    
        if ((/^[0-9]{4}$/).test(newValue)) {
          console.log("submitting...");
          try {
            const { idToken, refreshToken } = await authentication.answerCustomChallenge(`${newValue}`)
            console.log("submitted!!");
            setAuth(true);
            const redirectURL = `${localStorage.getItem('redirectURL')}?idToken=${idToken.getJwtToken()}&refreshToken=${refreshToken.getToken()}`;
            localStorage.removeItem('redirectURL')
            window.location = redirectURL;
          } catch (err) {
            toast('Please enter the right code.');
          }
        }
      }

However, this approach doesn't seem to be working as expected. I would appreciate any advice or guidance on how to achieve the desired behavior.

Thank you.

**Comment by SFaraji** [comment]
Found an alternative solution for the MuiOtpInput package. As of now (Aug. 15, 2023), the MuiOtpInput component does not support the input type 'number'. Instead, you can use the following package which does support the 'number' type: [react-otp-input](https://www.npmjs.com/package/react-otp-input).

**Comment by SFaraji** [comment]
@viclafouch can you please allow number inputType similar to above package from react-otp-input.

**Comment by viclafouch** [comment]
Hello @SFaraji !

Could you please try with this snippet : 

```tsx
<MuiOtpInput
        TextFieldsProps={{
          type: 'text',
          inputMode: 'numeric',
          size: 'medium'
        }}
        value={value}
        onChange={handleChange}
      />
```

**Comment by SFaraji** [comment]
To prevent the entry of illegal characters such as symbols and words and to ensure the use of a full numerical keyboard, you can use the following snippet:

   ```
<MuiOtpInput
      TextFieldsProps={{
        type: 'number',
        inputProps: {
          inputMode: 'numeric',
          pattern: '[0-9]*',
        },
        size: 'medium',
      }}
      value={otp}
      onChange={handleChange}
    />

```
