### ISSUE TITLE
Not working properly in Next JS

### ISSUE THREAD

**Issue by IntuzDarpitM** [viclafouch/mui-otp-input#33]
I am facing the below issue while using mui-otp-input in next js.

TypeError: react__WEBPACK_IMPORTED_MODULE_1___default(...).useInsertionEffect is not a function

![image](https://github.com/viclafouch/mui-otp-input/assets/105205496/90641d49-8934-4c9d-98c6-e3273ca4212e)

Anyone, please do needful.

**Comment by IntuzDarpitM** [comment]
Does anyone have any example in Next Js Please provide it, It will do needful.

**Comment by viclafouch** [comment]
Hello ! 

Could you please share a codesanbox reproduction plz ?

Are you using the last version of React?

Victor

**Comment by IntuzDarpitM** [comment]
Hello!

I am using React 17.0.2 with the next js version 12.1.6. It works properly with React version 18.2.0 and next js version 13.4.19.

**Comment by viclafouch** [comment]
Yep, only React 18 is supported.

**Comment by IntuzDarpitM** [comment]
Okay Thanks @viclafouch
