### ISSUE TITLE
Can not fill all OTP code in Chrome and DuckDuckGo

### ISSUE THREAD

**Issue by spartan-vutnguyen** [viclafouch/mui-otp-input#37]
I'm using this in my web app but when I open the app by Chrome and DuckDuckGo, it only fills the first number.
It works well in Safari

**Comment by viclafouch** [comment]
I don't understand the issue, 

Do you have a video or something else plz ?

**Comment by archieWu** [comment]
Hello, I encountered the same issue.
Here is my video.
[https://drive.google.com/file/d/1g4D92Sl3L7M8c5d-P9mYXvI6VB6UbtyM/view](video)

**Comment by spartan-vutnguyen** [comment]
Hi @viclafouch can you take a look?

**Comment by archieWu** [comment]
Hello, I found some issues and made modifications.
These modifications work fine in my project and achieve the expected results.
These appear to be errors resulting from different browser engines causing different behaviors.
[#42 ](https://github.com/viclafouch/mui-otp-input/pull/42)

**Comment by viclafouch** [comment]
Hey here ! 

I have also worked on this fix yesterday, let me check with my own and I will get back to you asap ;)

Ty !

**Comment by archieWu** [comment]
Hello, i see you was fix this bug.
but i see line 133.
you console forgot to delete.

**Comment by viclafouch** [comment]
Nah I removed it in the [next commit ](https://github.com/viclafouch/mui-otp-input/commit/2d58d041d33e4210401d4a0299ffa37a392a54c6) ;)
