### ISSUE TITLE
'MuiOtpInput' cannot be used as a JSX component - TypeScript Error

### ISSUE THREAD

**Issue by maxgertzen20** [viclafouch/mui-otp-input#43]
TS error in return function, also when using it with "styled" of mui/material.

`
'MuiOtpInput' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & RefAttributes<unknown>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & RefAttributes<unknown>>' is not assignable to type '(props: any) => ReactElement<any, any> | null'.
      Type 'ReactNode' is not assignable to type 'ReactElement<any, any> | null'.ts(2786)
(alias) const MuiOtpInput: React_2.ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & React_2.RefAttributes<unknown>>
import MuiOtpInput
`

![image](https://github.com/viclafouch/mui-otp-input/assets/92924026/2ab1e860-2778-450b-a322-79d10cd82300)

![image](https://github.com/viclafouch/mui-otp-input/assets/92924026/cb77ec59-1cc0-40bb-9ffb-01c8baa1c400)

**Comment by viclafouch** [comment]
Hello ! 

Could you please share a codesandbox plz ?

**Comment by maxgertzen20** [comment]
Hey, I couldn't reproduce it in codesandbox - https://codesandbox.io/s/otp-input-test-jj9lwy?file=/src/App.tsx

So, setting the TS version in VSCode seemed to solve the issue - for anyone who encountered it:

1. Ctrl + Shift + P
2. TypeScript: Select TypeScript Version
3. Use Workspace Version

![image](https://github.com/viclafouch/mui-otp-input/assets/92924026/4a3e3b62-7e18-4173-bd9a-5cb6f184d0ff)

![image](https://github.com/viclafouch/mui-otp-input/assets/92924026/cb5511b4-7199-4fd5-a63a-46372244b5c1)

@viclafouch Thanks for your quick response <3
