### ISSUE TITLE
Cannot use as JSX component

### ISSUE THREAD

**Issue by christopher-becker** [viclafouch/mui-otp-input#47]
Hi,

I've used this module on other projects and it works like a charm, but I recently installed the latest version 2 to a new project and I get the following error:

`'MuiOtpInput' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.ts(2786)
(alias) const MuiOtpInput: React_2.ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & React_2.RefAttributes<unknown>>
import MuiOtpInput`

Even when I use demo code of:

```
import React from "react";
import { MuiOtpInput } from "mui-one-time-password-input";

const MyComponent = () => {
  const [otp, setOtp] = React.useState("");

  const handleChange = (newValue: string) => {
    setOtp(newValue);
  };

  return (
    <MuiOtpInput value={otp} onChange={handleChange} />
  );
};
```

I get the same error.

Any help would be appreciated.

Thanks.

**Comment by viclafouch** [comment]
Hello ! 

Could you provide a codesandbox for reproduction plz ?

Victor

**Comment by thecodeinfluencer** [comment]
> Hi,
> 
> I've used this module on other projects and it works like a charm, but I recently installed the latest version 2 to a new project and I get the following error:
> 
> `'MuiOtpInput' cannot be used as a JSX component. Its return type 'ReactNode' is not a valid JSX element.ts(2786) (alias) const MuiOtpInput: React_2.ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & React_2.RefAttributes<unknown>> import MuiOtpInput`
> 
> Even when I use demo code of:
> 
> ```
> import React from "react";
> import { MuiOtpInput } from "mui-one-time-password-input";
> 
> const MyComponent = () => {
>   const [otp, setOtp] = React.useState("");
> 
>   const handleChange = (newValue: string) => {
>     setOtp(newValue);
>   };
> 
>   return (
>     <MuiOtpInput value={otp} onChange={handleChange} />
>   );
> };
> ```
> 
> I get the same error.
> 
> Any help would be appreciated.
> 
> Thanks.

Facing this issue currently

**Comment by thecodeinfluencer** [comment]
If you're still experiencing this issue, try these fixes (fix 1 worked for me):

1. Upgrade your `@types/react` in `devDependencies` to `18.2.25` (mine was initially`18.2.0`):

```
"devDependencies": {
    ...
    "@types/react": "18.2.25",
    ...
  },
```

2. Try [clearing your VS Code cache](https://bobbyhadz.com/blog/vscode-clear-cache)
