### ISSUE TITLE
setFocus (react-hook-form)

### ISSUE THREAD

**Issue by rattkin** [viclafouch/mui-otp-input#51]
how can I get setFocus (from react-hook-form) working?

Usually with custom form elements, like MuiTelInput I have to spread `ref` out of `<Controller` render prop `field` and assign it to the underlying mui input via `inputRef` prop.
Here however, there are multiple inputs in `TextFieldsProps`. I need to access only the first input.

IE this doesn't work:
```
<Controller
    control={control}
    rules={rules}
    name={props.name}
    render={({ field: { ref: fieldRef, ...fieldProps } }) => (
        <MuiOtpInput
            length={length}
            autoFocus={autoFocus}
            {...fieldProps}
            {...props}
            onComplete={onComplete}
            TextFieldsProps={{
                inputRef: fieldRef,
            }}
        />
    )}
/>
```

**Comment by rattkin** [comment]
I can try make a PR?

**Comment by viclafouch** [comment]
Thanks for the PR @rattkin !

Releasing...

**Comment by rattkin** [comment]
@viclafouch please reopen, the PR was only documentation improvement for tel-input.
I will do a proper PR.
