### ISSUE TITLE
Android device not showing number keyboard after adding number type

### ISSUE THREAD

**Issue by GittyAjay** [viclafouch/mui-otp-input#54]
<MuiOtpInput
                  value={otp}
                  // type="number"
                  itemType=''
                  type="number"
                  inputMode='numeric'
                  length={6}
                  gap={2}
                  TextFieldsProps={{ inputMode: 'numeric' }}
                  validateChar={(val) => !isNaN(val)}
                  onChange={handleChange}
                />

i have debugged type:"text" is not changing
![Screenshot 2024-03-01 at 12 08 57 PM](https://github.com/viclafouch/mui-otp-input/assets/43106735/85a49890-c14a-490a-bb1e-89e9c698628f)

**Comment by viclafouch** [comment]
Hello !

Could you please share a codesandbox for repro ?

Victor

**Comment by vishal-jiva** [comment]
We need to set `inputMode` on `inputProps` and not directly on `TextFieldsProps`

```TextFieldsProps={{ inputProps: { inputMode: "numeric" } }}```

https://codesandbox.io/p/sandbox/mui-one-time-password-input-forked-w62ml9
