### ISSUE TITLE
autofocus does not work on iOS devices

### ISSUE THREAD

**Issue by alextrukhan** [viclafouch/mui-otp-input#56]
when `autofocus` prop is provided, field is correctly focused and keyboard is show on android devices. for iOS devices `autoFocus` does not work, fields is shown as focused but there is no cursor in it and keyboard does not appear.

https://viclafouch.github.io/mui-otp-input/docs/api-reference/#autofocus

**Comment by pedegago** [comment]
Any progress on this? I am actually having the same problem and it is critial for my use case. `autoFocus` does not work on Chrome iOS and Safari iOS. Android devices looks like working as expected.

**Comment by alextrukhan** [comment]
@pedegago https://gist.github.com/cathyxz/73739c1bdea7d7011abb236541dc9aaa there is some info. think it wont be fixed, or maybe I've missed something

**Comment by viclafouch** [comment]
Hello ! Does someone has a solution ? I have no idea to fix it. So happy to get some help on this.

Thanks !

**Comment by shf60** [comment]
hey guys! 

now it just work on ios but not android.

version : V2.0.3

**Comment by viclafouch** [comment]
I think it's just a bug from browser, not the library..

**Comment by shf60** [comment]
> I think it's just a bug from browser, not the library..

you're right. The situation was on th develop but the problem solved when I built the project. 

#nextjs
