### ISSUE TITLE
Can MuiOtpInput give auto focus?

### ISSUE THREAD

**Issue by mohd-yusuf-quark** [viclafouch/mui-otp-input#57]
I have a OTP verification page.

I want the cursor to land on the first input by default but I am not able to do so. Is this even possible with MuiOtpInput ?

Here's the code:
```
    <Stack gap={1} >
      <Typography
        variant={'body2'}
        color={theme.palette.secondary.main}
      >Enter your 6 digit code</Typography>

      <MuiOtpInput
        value={otp}
        length={6}
        onChange={(value) => setOtp(value)}
        gap={1}
        validateChar={(value) => {
          return Boolean(value.match(/[0-9]/) && value.length === 1)
        }}
        TextFieldsProps={{
          inputProps: {
            style: {
              fontSize: '22px',
              padding: '10px 10px',
            }
          }
        }}
      />
```

      {otpError && <SelectHelperText selectHelperText={otpError} />}
    </Stack>
    
I tried to ask chatGPT, it was saying to add `autofocus `prop. I have already tried it, nothing happened.

**Comment by pedegago** [comment]
Hi, @mohd-yusuf-quark.
I think the current version already has support for autoFocus prop. In this release: https://github.com/viclafouch/mui-otp-input/releases/tag/v1.1.0
May be you are writing `autofocus` in lowercase insted of `autoFocus`.
