### ISSUE TITLE
export UDM version is required for Nextjs.

### ISSUE THREAD

**Issue by pedegago** [viclafouch/mui-otp-input#58]
Hi! I did an upgrade from version 1.x to 2.x but now i am having throubles with Nextjs. I have my Nextjs project into a NX monorepo.  Now i have to include the libray in my next.config.js file this way:
```
const nextConfig = {
  transpilePackages: ['mui-one-time-password-input'],
}
```
which is ugly for me. Before, i also include `"type": "module"` in my package.json but didnt work. Is there any official solution to this?

**Comment by viclafouch** [comment]
Hey @pedegago !

This is the correct solution, and not ugly at all ;)

The `transpilePackages` is very popular for ESM packages.

See https://github.com/viclafouch/mui-otp-input/issues/31#issuecomment-1676433147
