### ISSUE TITLE
Cannot use as JSX component (Reopen #47)

### ISSUE THREAD

**Issue by thecodeinfluencer** [viclafouch/mui-otp-input#59]
This is a reopen of #47 since it was closed with no solution

Below is issue description from [christopher-becker](https://github.com/christopher-becker) (the original author of #47 )

> Hi,
> 
> I've used this module on other projects and it works like a charm, but I recently installed the latest version 2 to a new project and I get the following error:
> 
> `'MuiOtpInput' cannot be used as a JSX component. Its return type 'ReactNode' is not a valid JSX element.ts(2786) (alias) const MuiOtpInput: React_2.ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & React_2.RefAttributes<unknown>> import MuiOtpInput`
> 
> Even when I use demo code of:
> 
> ```
> import React from "react";
> import { MuiOtpInput } from "mui-one-time-password-input";
> 
> const MyComponent = () => {
>   const [otp, setOtp] = React.useState("");
> 
>   const handleChange = (newValue: string) => {
>     setOtp(newValue);
>   };
> 
>   return (
>     <MuiOtpInput value={otp} onChange={handleChange} />
>   );
> };
> ```
> 
> I get the same error.
> 
> Any help would be appreciated.
> 
> Thanks.

[viclafouch](https://github.com/viclafouch) please keep this open for now in case any other person shares the same concern

**Comment by hannahlaek-wt** [comment]
Same thing happening to me. I'm using "react": "18.2.0",
and "next": "^14.2.3". No code snippet except importing the package into the file I need with import { MuiOtpInput } from "mui-one-time-password-input";

**Comment by viclafouch** [comment]
Hello !

Did you try this in your next config file ? 

```ts
const nextConfig = {
  transpilePackages: ['mui-one-time-password-input'],
}
```

**Comment by thecodeinfluencer** [comment]
@viclafouch you're quick to close this issue but the `transpilePackages` doesn't work either (I actually had it when raising this issue)

Smilar to @hannahlaek-wt, it's affecting all other JSX elements

**Comment by thecodeinfluencer** [comment]
@viclafouch kindly keep it open a bit longer

**Comment by viclafouch** [comment]
I need a repro guys.. How can I debug without a codesandbox ? 😭

**Comment by thecodeinfluencer** [comment]
If you're still experiencing this issue, try these fixes:

1. Upgrade your `@types/react` in `devDependencies` to `18.2.25` (mine was initially`18.2.0`):

```
"devDependencies": {
    ...
    "@types/react": "18.2.25",
    ...
  },
```

2. [Clear your VS Code cache](https://bobbyhadz.com/blog/vscode-clear-cache)

- Fix 1 worked for me

**Comment by AhsanImtiazRafiq** [comment]
'MuiOtpInput' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & RefAttributes<unknown>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<Omit<MuiOtpInputProps, "ref"> & RefAttributes<unknown>>' is not assignable to type '(props: any) => ReactNode | Promise<ReactNode>'.
      Type 'ReactNode' is not assignable to type 'ReactNode | Promise<ReactNode>'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode | Promise<ReactNode>'.
          Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
index.d.ts(387, 9): 'children' is declared here.

Facing similer issue
