### ISSUE TITLE
Takes and Gives only Strings as Value Property

### ISSUE THREAD

**Issue by khvalery-rakbank** [viclafouch/mui-otp-input#60]
It throws an error when I try to pass a number as a value, and what is even more critic it returns only string instead of initial number.
So it's incompatible with TypeSafety libraries like Zod, Yup, ect.

**Comment by viclafouch** [comment]
Hello ! 

This library is compatible with zod, yup, etc.. Just don't give a number, but a string.. Don't understand your point here.
