### ISSUE TITLE
Error while creating build with yarn and vite.

### ISSUE THREAD

**Issue by gcsandesh** [viclafouch/mui-otp-input#61]
I was using this package in one of my projects and I was creating a build for deployment while I encountered this error.

The project is a react application created with vite, and I am using 'yarn' package manager, the node version is 20. 

I also tried manually installing '@mui/utils' package but it did not solve the problem. Also in the error message it suggests externalizing the module but I don't want to do it. 

Is this a problem with vite or with the package?
I am not looking for the solution for myself, I will use another package for the project. I am only reporting the issue that I encountered.

![image](https://github.com/viclafouch/mui-otp-input/assets/59115123/d661f09e-1534-4b36-aa17-d5a3add72637)

**Comment by viclafouch** [comment]
Hello ! Do you have still the error ?

**Comment by gcsandesh** [comment]
I had to remove this package from the project due to the issue.
