### ISSUE TITLE
How do we restrict user to edit only from Right to Left

### ISSUE THREAD

**Issue by vikramrobosoft** [viclafouch/mui-otp-input#63]
"As a user, I would like to be able to edit the OTP value. For example, if the OTP is '1010' and I accidentally type '1110', when I delete the '1' from the first index, the values shift and appear as '110[Empty]', which creates a poor user experience. Can we restrict editing to only allow modifications from right to left?"

**Comment by viclafouch** [comment]
Hello ! 

Sorry, that's not how the logic was created.. Some people want the current solution :/
