### ISSUE TITLE
Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by npyvovartseva** [viclafouch/mui-otp-input#64]
Good day.
Can you please help me?

After upgrading to version: 2.0.3 I get an error:
Cannot read properties of null (reading 'useRef')

It worked perfectly with 2.0.2.
My project is on react: v18.2.0

Thank you.

**Comment by viclafouch** [comment]
What's your bundle config ?

**Comment by xjmardia** [comment]
Same issue here. I tried with those react and react-dom versions with mui-otp-input 2.0.3 version but it still doesn't work.
