### ISSUE TITLE
dependency conflict 

### ISSUE THREAD

**Issue by zaber-ahmed-selise** [viclafouch/mui-otp-input#69]
"dependencies": {
        "@emotion/react": "^11.11.4",
        "@emotion/styled": "^11.11.5",
        "@mui/material": "^5.16.0",
        "@types/react": "^18.3.3",
        "react": "^18.3.1",
        "react-dom": "^18.3.1"
      },
      
      Suppose I am running @mui/material below 5.16, or react below 18.3.1 shouldn't I have warnings when I am trying to install this package?

**Comment by viclafouch** [comment]
Hello !

This package has a new release with all dependencies updated !
See https://github.com/viclafouch/mui-otp-input/releases/tag/v3.0.0

Thanks for your help !
