### ISSUE TITLE
select() the last input item on complete

### ISSUE THREAD

**Issue by ggepenyan** [viclafouch/mui-otp-input#9]
expected result: last input should be focused or the cursor should not appear for any input.
actual result: the cursor stays on the last input and on change is not working.

It is not working the way it intent.
I have added these lines to my code. I can open a PR for this because I think this behavior is not working correctly:
`const focusLastInput = () => {
    if (!inputRef.current?.lastChild) {
      return;
    }
    const lastInputBox = inputRef.current.lastChild as HTMLDivElement;
    const lastInput = lastInputBox.querySelector('input');
    if (lastInput) {
      lastInput.select();
    }
  };`

**Comment by viclafouch** [comment]
Hey ! 

I think there is a conflict with this issue I resolved weeks ago..

https://github.com/viclafouch/mui-otp-input/issues/1

Looks like nobody are agree ^^
